base: &base
  encoding: utf8
  adapter: mysql2
  socket: /private/tmp/mysql.sock
  database: stocks_development
  username: root
  
development:
  <<: *base
  database: stocks_development
  
test:
  <<: *base
  database: stocks_test